Repository book-cord/book-cord, pull requests merged in 2022-06, with the labels that each got.

#8 헤더 구현
  .gitignore
  src/views/common/header/header.css
  src/views/common/header/header.js
  src/views/images/logo.png
  src/views/login/login.css
  src/views/login/login.html
  src/views/login/login.js
Labels: enhancement, sojeong

#11 Heejin
  src/views/common/footer/footer.css
  src/views/common/footer/footer.js
Labels: enhancement, question, heejin

#13 Heejin
  src/views/common/reset.css
Labels: enhancement, heejin

#15 header CSS 수정
  src/views/common/header/header.css
Labels: enhancement, heejin

#17 회원가입 페이지 구현
  src/views/signIn/signIn.css
  src/views/signIn/signIn.html
Labels: enhancement, sojeong

#19 탭메뉴 모듈화
  src/views/common/header/header.css
  src/views/common/header/header.js
  src/views/common/tabButton/tabButton.css
  src/views/common/tabButton/tabButton.js
Labels: enhancement, sojeong

#20 css 반응형
  src/views/common/footer/footer.css
  src/views/common/header/header.css
  src/views/login/login.css
Labels: enhancement, sojeong

#21 독서기록 페이지 구현
  src/views/common/tabButton/tabButton.js
  src/views/record/record.css
  src/views/record/record.html
  src/views/record/record.js
Labels: enhancement, sojeong

#22 feat: 독서 기록 스타일 오류 수정
  src/views/record/record.css
  src/views/record/record.js
Labels: enhancement, sojeong

#24 랜딩페이지 구현
  src/views/landing/images/bookImage1.png
  src/views/landing/images/bookImage2.jpeg
  src/views/landing/images/bookImage3.jpeg
  src/views/landing/landing.css
  src/views/landing/landing.html
  src/views/landing/landing.js
Labels: enhancement, heejin
