Repository book-cord/book-cord, pull requests merged in 2022-07, with the labels that each got.

#27 feat: reset css 수정
  src/views/common/reset.css
Labels: enhancement, heejin

#32 unitRecord로 데이터를 보내기위한 코드 추가
  src/views/myBook/myBook.css
  src/views/myBook/myBook.js
  src/views/myRecord/myRecord.js
Labels: enhancement, sojeong

#34 개별 독서기록 페이지 구현
  src/views/uniRecord/unitRecord.css
  src/views/uniRecord/unitRecord.html
  src/views/uniRecord/unitRecord.js
Labels: enhancement, heejin

#36 개별 독서 기록페이지 구현
  src/views/common/reset.css
  src/views/myBook/myBook.js
  src/views/myRecord/myRecord.js
  src/views/record/record.js
  src/views/uniRecord/unitRecord.css
  src/views/uniRecord/unitRecord.html
  src/views/uniRecord/unitRecord.js
Labels: enhancement, sojeong, heejin

#41 로컬 스토리지 구조 변경
  src/views/record/record.js
Labels: enhancement, sojeong, refactoring

#42 로컬스토리지 구조 변경
  src/views/myBook/myBook.js
Labels: enhancement, sojeong, refactoring

#43 로컬스토리지 구조 변경
  src/views/myRecord/myRecord.js
Labels: enhancement, sojeong, refactoring

#44 로그인 페이지 구현
  src/views/login/login.css
  src/views/login/login.html
  src/views/login/login.js
  src/views/myBook/myBook.js
Labels: enhancement, sojeong, refactoring

#51 feat: reset css 수정
  src/views/common/reset.css
Labels: enhancement, heejin

#53 feat: myRecord 페이지 - 오류 수정
  src/views/myRecord/myRecord.css
  src/views/myRecord/myRecord.js
Labels: bug, sojeong

#57 준비중인 서비스모달 모듈화
  src/views/common/header/header.js
  src/views/common/notAvailableModal/notAvailableModal.css
  src/views/common/notAvailableModal/notAvailableModal.js
  src/views/common/tabButton/tabButton.js
  src/views/landing/landing.css
  src/views/landing/landing.html
  src/views/login/login.css
  src/views/login/login.html
  src/views/login/login.js
  src/views/modifyRecord/modifyRecord.css
  src/views/modifyRecord/modifyRecord.html
  src/views/myBook/myBook.css
  src/views/myBook/myBook.html
  src/views/myRecord/myRecord.css
  src/views/myRecord/myRecord.html
  src/views/record/record.css
  src/views/record/record.html
  src/views/signIn/signIn.css
  src/views/signIn/signIn.html
  src/views/uniRecord/unitRecord.css
  src/views/uniRecord/unitRecord.html
Labels: enhancement, sojeong, heejin

#59 fix: 상수 중복 에러를 해결하였습니다.
  src/views/login/login.js
Labels: bug, sojeong, heejin

#60 fix: 모달 관련 이슈 수정
  src/views/login/login.js
Labels: bug, sojeong, heejin

#63 feat: 북코드 로딩페이지 구현
  bookcord-after.svg
  bookcord-before.svg
  index.css
  index.html
  index.js
Labels: enhancement, sojeong, heejin

#68 feat: 모바일 사이즈 반응형 웹 대응
  src/views/common/header/header.css
  src/views/common/tabButton/tabButton.css
  src/views/myRecord/myRecord.css
  src/views/record/record.css
Labels: enhancement, heejin

#69 feat: 로그인할 때 닉네임이 3글자 초과되면 UI무너지는 이슈
  src/views/login/login.html
  src/views/login/login.js
Labels: enhancement, sojeong
